#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

ln -sf $DOTFILES/gitignore_global $HOME/.gitignore_global

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/deliver $HOME/.local/bin/deliver

mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

# install astrovim
rm -rf $HOME/.config/nvim

git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim

rm -rf $HOME/.config/nvim/lua/user
ln -s $DOTFILES/nvim/user $HOME/.config/nvim/lua/user 

nvim +PackerSync

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

git clone https://github.com/jessarcher/zsh-artisan.git $HOME/.oh-my-zsh/custom/plugins/artisan

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
